### ISSUE TITLE
提问个问题

### ISSUE THREAD

**Issue by mouse-lin** [mojimomo/PlanIt#1]
我看到很多第三库，如: MBProgressHUD、MobClick、PopupDialog 这些为什么不在 Pod 里面固定版本然后引入，而是要直接放在 Venders 里面

**Comment by mojimomo** [comment]
因为某些需求改动了不少库，还有Swfit每个改动较大，每个版本库可能会不能使用，所以没有使用pod集中管理。

**Comment by mouse-lin** [comment]
原来这样，明白。
